# my global config
global:
  scrape_interval: 3s
  evaluation_interval: 3s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ] # Only works on Docker Desktop for Mac
  - job_name: 'docker'
    static_configs:
      - targets: [ 'host.docker.internal:9323' ]
#  - job_name: cadvisor
#    scrape_interval: 3s
#    static_configs:
#      - targets:
#          - cadvisor:8098
  - job_name: gonode1
    scrape_interval: 3s
    static_configs:
      - targets:
          - api1:8090
  - job_name: gonode2
    scrape_interval: 3s
    static_configs:
      - targets:
          - api2:8091
  - job_name: gonode3
    scrape_interval: 3s
    static_configs:
      - targets:
          - api3:8092
